name: Publish

on:
  workflow_call:
    inputs:
      distribution:
        description: 'Java distribution. See the list of supported distributions in README file'
        default: 'temurin'
        type: string
        required: false
      java-version:
        description: 'The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file'
        default: '17'
        type: string
        required: false
      cache:
        description: 'Name of the build platform to cache dependencies. It can be "maven", "gradle" or "sbt".'
        default: 'gradle'
        type: string
        required: false
    secrets:
      maven-user:
        description: 'Username for Gradle/Maven repository'
        required: false
      maven-password:
        description: 'Password/token for Gradle/Maven repository'
        required: false
      curseforge-id:
        description: 'Curseforge project ID'
        required: true
      curseforge-token:
        description: 'Curseforge access token'
        required: true
      modrinth-id:
        description: 'Modrinth project ID'
        required: true
      modrinth-token:
        description: 'Modrinth access token'
        required: true

jobs:
  publish-maven:
    name: Publish to Maven
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[publish]')

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ inputs.distribution }}
          java-version: ${{ inputs.java-version }}
          cache: ${{ inputs.cache }}
      - uses: gradle/wrapper-validation-action@v1
      - name: Publish with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          MAVEN_USER: ${{ secrets.maven-user }}
          MAVEN_TOKEN: ${{ secrets.maven-password }}
      - name: Remove Extra JARs
        run: rm -f {fabric,forge}/build/libs/*{sources,dev,shadow}*.jar
      - name: Move Fabric JARs
        run: for f in fabric/build/libs/*.jar; do mv "$f" "${f/.jar/-fabric.jar}"; done
      - name: Move Forge JARs
        run: for f in forge/build/libs/*.jar; do mv "$f" "${f/.jar/-forge.jar}"; done
      - name: Box Fabric JARs
        uses: actions/upload-artifact@v3
        with:
          name: fabric
          path: fabric/build/libs
      - name: Box Forge JARs
        uses: actions/upload-artifact@v3
        with:
          name: forge
          path: forge/build/libs

  publish-github:
    name: Release to Github
    needs: publish-maven
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Unbox Fabric JARs
        uses: actions/download-artifact@v3
        with:
          name: fabric
          path: build/libs
      - name: Unbox Forge JARs
        uses: actions/download-artifact@v3
        with:
          name: forge
          path: build/libs
      - uses: Kir-Antipov/mc-publish@v3.2
        with:
          github-token: ${{ github.token }}
          github-generate-changelog: true
          files: "build/libs/*.jar"

  publish-fabric:
    name: Release Fabric version
    needs: publish-maven
    runs-on: ubuntu-latest

    steps:
      - name: Unbox Fabric JARs
        uses: actions/download-artifact@v3
        with:
          name: fabric
          path: build/libs
      - uses: Kir-Antipov/mc-publish@v3.2
        with:
          loaders: fabric
          modrinth-id: ${{ secrets.modrinth-id }}
          modrinth-token: ${{ secrets.modrinth-token }}
          curseforge-id: ${{ secrets.curseforge-id }}
          curseforge-token: ${{ secrets.curseforge-token }}
          files: "build/libs/*-fabric.jar"

  publish-forge:
    name: Publish Forge version to Curseforge and Modrinth
    needs: publish-maven
    runs-on: ubuntu-latest

    steps:
      - name: Unbox Forge JARs
        uses: actions/download-artifact@v3
        with:
          name: forge
          path: build/libs
      - uses: Kir-Antipov/mc-publish@v3.2
        with:
          loaders: forge
          modrinth-id: ${{ secrets.modrinth-id }}
          modrinth-token: ${{ secrets.modrinth-token }}
          curseforge-id: ${{ secrets.curseforge-id }}
          curseforge-token: ${{ secrets.curseforge-token }}
          files: "build/libs/*-forge.jar"
