name: Publish

on:
  workflow_call:
    inputs:
      git-email:
        description: 'Email address to use for git commit'
        default: 'github-actions@github.com'
        type: string
        required: false
      git-user:
        description: 'Username to use for git commit'
        default: 'github-actions'
        type: string
        required: false
      distribution:
        description: 'Java distribution. See the list of supported distributions in README file'
        default: 'temurin'
        type: string
        required: false
      java-version:
        description: 'The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file'
        default: '17'
        type: string
        required: false
      cache:
        description: 'Name of the build platform to cache dependencies. It can be "maven", "gradle" or "sbt".'
        default: 'gradle'
        type: string
        required: false
    secrets:
      github-token:
        description: 'Token to use for pushing back to GitHub'
        required: true
      maven-user:
        description: 'Username for Gradle/Maven repository'
        required: false
      maven-password:
        description: 'Password/token for Gradle/Maven repository'
        required: false
      curseforge-id:
        description: 'Curseforge project ID'
        required: true
      curseforge-token:
        description: 'Curseforge access token'
        required: true
      modrinth-id:
        description: 'Modrinth project ID'
        required: true
      modrinth-token:
        description: 'Modrinth access token'
        required: true

jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.base.ref }}
          token: ${{ secrets.github-token }}
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ inputs.distribution }}
          java-version: ${{ inputs.java-version }}
          cache: ${{ inputs.cache }}
      - uses: gradle/wrapper-validation-action@v1
      - name: Git config
        run: |
          git config --global user.email ${{ inputs.git-email }}
          git config --global user.name ${{ inputs.git-user }}
      - name: Bump version as-is
        uses: gradle/gradle-build-action@v2
        if: join(github.event.pull_request.labels.*.name, '') == ''
        with:
          arguments: releaseVersion
      - name: Bump alpha version
        uses: gradle/gradle-build-action@v2
        if: contains(github.event.pull_request.labels.*.name, 'alpha')
        with:
          arguments: releaseVersion --preRelease=alpha.1
      - name: Bump beta version
        uses: gradle/gradle-build-action@v2
        if: contains(github.event.pull_request.labels.*.name, 'beta')
        with:
          arguments: releaseVersion --preRelease=beta.1
      - name: Bump rc version
        uses: gradle/gradle-build-action@v2
        if: contains(github.event.pull_request.labels.*.name, 'rc')
        with:
          arguments: releaseVersion --preRelease=rc.1
      - name: Promote version
        uses: gradle/gradle-build-action@v2
        if: contains(github.event.pull_request.labels.*.name, 'promote')
        with:
          arguments: releaseVersion --preRelease=-
      - name: Commit version
        run: git push --follow-tags
      - name: Publish
        uses: gradle/gradle-build-action@v2
        if: contains(github.event.pull_request.labels.*.name, 'no-publish')
        with:
          arguments: publish publishUnified
        env:
          MAVEN_USER: ${{ secrets.maven-user }}
          MAVEN_TOKEN: ${{ secrets.maven-password }}
          CURSEFORGE_ID: ${{ secrets.curseforge-id }}
          CURSEFORGE_TOKEN: ${{ secrets.curseforge-token }}
          MODRINTH_ID: ${{ secrets.modrinth-id }}
          MODRINTH_TOKEN: ${{ secrets.modrinth-token }}
