name: Bump Version

on:
  workflow_call:
    inputs:
      git-email:
        description: 'Email address to use for git commit'
        default: 'github-actions@github.com'
        type: string
        required: false
      git-user:
        description: 'Username to use for git commit'
        default: 'github-actions'
        type: string
        required: false
      commit-message:
        description: 'Commit message to use for version bump'
        default: 'Version bump'
        type: string
        required: false
      distribution:
        description: 'Java distribution. See the list of supported distributions in README file'
        default: 'temurin'
        type: string
        required: false
      java-version:
        description: 'The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file'
        default: '17'
        type: string
        required: false
      cache:
        description: 'Name of the build platform to cache dependencies. It can be "maven", "gradle" or "sbt".'
        default: 'gradle'
        type: string
        required: false

jobs:
  bump:
    name: Bump Version
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ inputs.distribution }}
          java-version: ${{ inputs.java-version }}
          cache: ${{ inputs.cache }}
      - uses: gradle/wrapper-validation-action@v1
      - name: Git config
        run: |
          git config --global user.email ${{ inputs.git-email }}
          git config --global user.name ${{ inputs.git-user }}
      - name: Apply version bump (major)
        if: contains(github.event.pull_request.labels.*.name, 'major')
        uses: gradle/gradle-build-action@v2
        with:
          arguments: incrementSemanticVersion --major
      - name: Apply version bump (minor)
        if: contains(github.event.pull_request.labels.*.name, 'minor')
        uses: gradle/gradle-build-action@v2
        with:
          arguments: incrementSemanticVersion --minor
      - name: Apply version bump (patch)
        if: contains(github.event.pull_request.labels.*.name, 'patch')
        uses: gradle/gradle-build-action@v2
        with:
          arguments: incrementSemanticVersion --patch
      - name: Commit version bump
        run: |
          git add version.properties
          git commit -m "${{ inputs.commit-message }} [skip-deploy]"
          git push
